tosca_definitions_version: tosca_simple_yaml_1_0

node_types: 
  
  my.nodes.VM.OpenStack:
    derived_from: tosca.nodes.Compute
    properties:
      name:
        type: string
        description: Name that should be given to the VM in OpenStack
      image:
        type: string
        description: OpenStack image id (image names are not accepted)
      flavor:
        type: string
        description: OpenStack flavor id (flavor names are not accepted)
      network:
        type: string
        description: OpenStack network id (network names are not accepted)
      key_name:
        type: string
        description: OpenStack SSH key name that should be placed on the VM
      boot_from_volume:
        type: boolean
        description: true_if it has to boot from a volume else_false
      volume_size:
        type: integer
        description: size of vloume in GB 
      boot_volume:
        type: string
        description: boot from the given volume id
    attributes:
      id:
        type: string
        description: OpenStack id of the VM
    interfaces:
      Standard:
        type: tosca.interfaces.node.lifecycle.Standard
        create:
          inputs:
            vm_name:  { default: { get_property: [ SELF, name     ] } }
#            image:    { default: { get_property: [ SELF, image    ] } }
            flavor:   { default: { get_property: [ SELF, flavor   ] } }
            network:  { default: { get_property: [ SELF, network  ] } }
            key_name: { default: { get_property: [ SELF, key_name ] } }
            boot_from_volume: { default: { get_property: [ SELF, boot_from_volume ] } }
            boot_volume: { default: { get_property: [ SELF, boot_volume ] } }
          implementation: playbooks/createVM.yml
        

  my.nodes.app:
    derived_from: tosca.nodes.SoftwareComponent        
    interfaces:
      Standard:
        type: tosca.interfaces.node.lifecycle.Standard
        create:
          implementation:
            primary: playbooks/deployApp.yml

topology_template:
  node_templates:
    vm1:
      type: my.nodes.VM.OpenStack
      properties:
        name: nginx_host
#        image: d3eeb4ae-9b8c-49ed-8314-123a8a808b2b
        flavor: 99156937-1374-4eb7-89c0-639217eba7d4
        network: 7c9f4afb-fff3-4729-9d37-2082f74e4096
        key_name: rem-VM2
        boot_from_volume: True
        boot_volume: 365ee0bb-cb8c-4ac4-952a-52d659e7449a


    app1:
      type: my.nodes.app
      requirements:
        - host: vm1
    
    
