tosca_definitions_version: tosca_simple_yaml_1_0

node_types: 
  
  my.nodes.VM.OpenStack:
    derived_from: tosca.nodes.Compute
    attributes:
      id:
        type: string
        description: OpenStack id of the VM
    interfaces:
      Standard:
        type: tosca.interfaces.node.lifecycle.Standard
        create:
          implementation: playbooks/vm.yml
        delete:
          inputs:
            id: { default: { get_attribute: [ SELF, id ] } }
          implementation: playbooks/vm/delete.yml

  my.nodes.Nginx:
    derived_from: tosca.nodes.SoftwareComponent
    attributes:
      site_config_dir:
        type: string
        description: Location of nginx site configs
    capabilities:
      host:
        type: tosca.capabilities.Compute
        valid_source_types: [my.nodes.Nginx.Site]
    

  my.nodes.Nginx.Site:
    derived_from: tosca.nodes.SoftwareComponent
    requirements:
      - host:
          capability: tosca.capabilities.Compute
          relationship: my.relationships.NginxSiteHosting

  

relationship_types:
  my.relationships.NginxSiteHosting:
    derived_from: tosca.relationships.HostedOn
    valid_target_types: [my.nodes.Nginx]
    interfaces:
      Configure:
        add_source:
          implementation:
            primary: playbooks/nginx/reload.yml

 


topology_template:
  node_templates:
    vm1:
      type: my.nodes.VM.OpenStack

    nginxServer1:
      type: my.nodes.Nginx
      requirements:
        - host: vm1

    app1:
      type: my.nodes.Nginx.Site
      requirements:
        - host: nginxServer1
      interfaces:
        Standard:          
          create: playbooks/getinfo.yml
          
    
